/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPackage;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Joy
 */
public class Vote extends javax.swing.JFrame {

    Connection conn = null;
    Statement stm = null;
    ResultSet rst = null;
    PreparedStatement pst = null;
   
    public Vote() {
        initComponents();
        fillCombo();
    }
    public void fillCombo(){
       
          connectAdmin konny = new connectAdmin();
          conn = konny.Connectdb(); 
       
            String sql = "Select * from candidate where position ='President' ";
             try{
                 pst= conn.prepareStatement(sql);   
                 rst = pst.executeQuery();
                 while(rst.next()){ 
                        String a = rst.getString("fname");
                        String b = rst.getString("sname");
                         jComboBox2.addItem(a +" "+ b);
                 }
                }
             catch(Exception ex){
                  JOptionPane.showMessageDialog(this, ex.getMessage());
                
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PRESIDENT = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2), "WELCOME TO K.O.V.S!!!", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Bodoni MT", 1, 24), new java.awt.Color(0, 51, 0))); // NOI18N
        jPanel1.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 0));
        jLabel1.setText("VOTE FOR");

        PRESIDENT.setFont(new java.awt.Font("Bodoni MT Condensed", 1, 18)); // NOI18N
        PRESIDENT.setText("President");
        PRESIDENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRESIDENTActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Bodoni MT Condensed", 1, 18)); // NOI18N
        jButton3.setText("Vice President");

        jComboBox1.setFont(new java.awt.Font("Bodoni MT Condensed", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "President", "Vice President", "Treasure", "Public Secretary", "Organizing Secretary", "Secretary", "4TH Year Representative", "3RD Year Representative", "2ND Year Representative", "1ST Year Representative", " " }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Bodoni MT Condensed", 1, 17)); // NOI18N
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });

        jComboBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jComboBox3MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(PRESIDENT)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(568, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {PRESIDENT, jButton3});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PRESIDENT)
                    .addComponent(jButton3))
                .addGap(44, 44, 44)
                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {PRESIDENT, jButton3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
               
        String s = jComboBox1.getSelectedItem().toString();
        
         connectAdmin konny = new connectAdmin();
         conn = konny.Connectdb(); 
         /**         * 
                4TH Year Representative 3RD Year Representative 2ND Year Representative 1ST Year Representative
          */
          if(s.contains("President")){
              String sql = "Select * from candidate where position ='President' ";
              try{
                 pst= conn.prepareStatement(sql);   
                 rst = pst.executeQuery();
                 while(rst.next()){ 
                        String a = rst.getString("fname");
                        String b = rst.getString("sname");
                        jComboBox2.addItem(a +" "+ b);}}
             catch(Exception ex){
                  JOptionPane.showMessageDialog(this, ex.getMessage());}}
          else if(s.contains("Vice President")){
              String sql = "Select * from candidate where position ='Vice President' ";
              try{
                 pst= conn.prepareStatement(sql);   
                 rst = pst.executeQuery();
                 while(rst.next()){ 
                        String a = rst.getString("fname");
                        String b = rst.getString("sname");
                        jComboBox2.addItem(a +" "+ b);}}
             catch(Exception ex){
                  JOptionPane.showMessageDialog(this, ex.getMessage());}}
          else if(s.contains("Treasure")){
              String sql = "Select * from candidate where position ='Treasure' ";
              try{
                 pst= conn.prepareStatement(sql);   
                 rst = pst.executeQuery();
                 while(rst.next()){ 
                        String a = rst.getString("fname");
                        String b = rst.getString("sname");
                        jComboBox2.addItem(a +" "+ b);}}
             catch(Exception ex){
                  JOptionPane.showMessageDialog(this, ex.getMessage());}}
           else if(s.contains("Public Secretary")){
              String sql = "Select * from candidate where position ='Public Secretary' ";
              try{
                 pst= conn.prepareStatement(sql);   
                 rst = pst.executeQuery();
                 while(rst.next()){ 
                        String a = rst.getString("fname");
                        String b = rst.getString("sname");
                        jComboBox2.addItem(a +" "+ b);}}
             catch(Exception ex){
                  JOptionPane.showMessageDialog(this, ex.getMessage());}}
          else if(s.contains("Organizing Secretary")){
              String sql = "Select * from candidate where position ='Organizing Secretary' ";
              try{
                 pst= conn.prepareStatement(sql);   
                 rst = pst.executeQuery();
                 while(rst.next()){ 
                        String a = rst.getString("fname");
                        String b = rst.getString("sname");
                        jComboBox2.addItem(a +" "+ b);}}
             catch(Exception ex){
                  JOptionPane.showMessageDialog(this, ex.getMessage());}}
         if(s.contains("Secretary")){
              String sql = "Select * from candidate where position ='Secretary' ";
              try{
                 pst= conn.prepareStatement(sql);   
                 rst = pst.executeQuery();
                 while(rst.next()){ 
                        String a = rst.getString("fname");
                        String b = rst.getString("sname");
                        jComboBox2.addItem(a +" "+ b);}}
             catch(Exception ex){
                  JOptionPane.showMessageDialog(this, ex.getMessage());}}
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void PRESIDENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRESIDENTActionPerformed
        
    }//GEN-LAST:event_PRESIDENTActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged

    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox3MouseEntered
       jComboBox3.showPopup();
    }//GEN-LAST:event_jComboBox3MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PRESIDENT;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
